version: '3.8'

services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    user: 1000:1000
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    user: 1000:1000
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    user: 1000:1000
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    # stdin_open: true #-i
    # tty: true #-t
    volumes:
      - ./src:/var/www/html
    user: 1000:1000
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    #overwrite or add entry point if it doesn't exist
    entrypoint: [ "php", "/var/www/html/artisan" ]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
